#!/bin/bash
source .credentials
dsmadmc -id=${TSMUSER} -pa=${TSMPASS} -OUTfile=/tmp/tsm-mp4-query -COMMAdelimited "select contents.file_name, volumes.STGPOOL_NAME from contents, volumes where contents.filespace_name='/gpfs/archive' and contents.segment!='2/2' and contents.file_name LIKE '/prod/%.mp4' and volumes.volume_name = contents.volume_name order by contents.file_name"
echo "Results saved to /tmp/tsm-mp4-query"
