#!/bin/bash
# -------------------------------------------------------------------------------
# Name: tsm_backup_prepare
# Description: Backs up daily prepre scripts that are created during the DRM
# PREPARE process.
#
# Additionally, the required database recovery volumes are compressed, and copied
# to a backup location along with the associated prepare script.  Each day's 
# backup will be named with the date of the backup and contain the prepre script
# along with the required database backup voumes.  Backups will also be rotated
# on a scheduled basis.
#
# Adam Wead
# Rock and Roll Hall of Fame
# Library and Archives
# -------------------------------------------------------------------------------

# -------------------------------------------------------------------------------
#
# Config
#
# -------------------------------------------------------------------------------

# Directory where the plan scripts are stored
# i.e. the output from the PREPARE command
PLANDIR="/opt/tivoli/drm/plans"

# Directory where recovery "volumes" are stored
RCVRDIR="/opt/tivoli/rdb/recovery"

# Directory where you'd like the data copied
BKUPDIR="/opt/tivoli/Dropbox"

# Directory where this script is installed
INSTDIR="/opt/tsm_scripts"

# Number of days to keep old files
OLDDAYS=10

# -------------------------------------------------------------------------------
#
# Begin main
#
# -------------------------------------------------------------------------------

DATE=`date +%Y%m%d`

# explode plan file
awk -f ${INSTDIR}/planexpl.awk ${PLANDIR}/${DATE}.*

echo "Creating dated directory under ${BKUPDIR}"
mkdir -p ${BKUPDIR}/${DATE}

# get required recovery volumes
for RVOL in `grep ${RCVRDIR} ${PLANDIR}/RECOVERY.VOLUMES.REQUIRED | /bin/awk '{print tolower($0)}'`
do
  echo "Compressing ${RVOL} to ${BKUPDIR}"
  gzip -c ${RVOL} > ${BKUPDIR}/${DATE}/`basename ${RVOL}`.gz
done

echo "Copying plan file to ${BKUPDIR}"
cp ${PLANDIR}/${DATE}.* ${BKUPDIR}/${DATE}

# clean up
echo "Removing exploded files"
rm -f ${PLANDIR}/RECOVERY.INSTRUCTIONS.GENERAL
rm -f ${PLANDIR}/RECOVERY.INSTRUCTIONS.OFFSITE
rm -f ${PLANDIR}/RECOVERY.INSTRUCTIONS.INSTALL
rm -f ${PLANDIR}/RECOVERY.INSTRUCTIONS.DATABASE
rm -f ${PLANDIR}/RECOVERY.INSTRUCTIONS.STGPOOL
rm -f ${PLANDIR}/RECOVERY.VOLUMES.REQUIRED
rm -f ${PLANDIR}/RECOVERY.DEVICES.REQUIRED
rm -f ${PLANDIR}/RECOVERY.SCRIPT.DISASTER.RECOVERY.MODE
rm -f ${PLANDIR}/RECOVERY.SCRIPT.NORMAL.MODE
rm -f ${PLANDIR}/DB.STORAGEPATHS
rm -f ${PLANDIR}/LICENSE.REGISTRATION
rm -f ${PLANDIR}/ACTIVEDATASTGPOOL.VOLUMES.AVAILABLE
rm -f ${PLANDIR}/ACTIVEDATASTGPOOL.VOLUMES.DESTROYED
rm -f ${PLANDIR}/COPYSTGPOOL.VOLUMES.AVAILABLE
rm -f ${PLANDIR}/COPYSTGPOOL.VOLUMES.DESTROYED
rm -f ${PLANDIR}/PRIMARY.VOLUMES.DESTROYED
rm -f ${PLANDIR}/PRIMARY.VOLUMES.REPLACEMENT
rm -f ${PLANDIR}/STGPOOLS.RESTORE
rm -f ${PLANDIR}/VOLUME.HISTORY.FILE
rm -f ${PLANDIR}/DEVICE.CONFIGURATION.FILE
rm -f ${PLANDIR}/DSMSERV.OPT.FILE

echo "Removing old backups"
find ${BKUPDIR} -name "`date +%Y`*" -type d -ctime ${OLDDAYS} | xargs rm -Rf
