#!/bin/bash
# -------------------------------------------------------------------------------
# Name: tsm_failures
# Description: Queries the activity log for result codes ANR09 in the previous
# 24 hours.  This is turn is checked for any failures and reported to stdout.
#
# Adam Wead
# Rock and Roll Hall of Fame
# Library and Archives
# -------------------------------------------------------------------------------
source .credentials

OUTFILE="/tmp/tsm-failures"
COMMAND="q actlog begindate=today-1 search=ANR09"

dsmadmc -id=${TSMUSER} -pa=${TSMPASS} -Q -OUTfile=${OUTFILE} -COMMAdelimited "${COMMAND}" > /dev/null
RESULTS=`cat ${OUTFILE} | grep FAIL`

if [ -n "${RESULTS}" ]; then
  echo ${RESULTS}
  exit 1;
else
  exit 0;
fi
